template = "https://github.com/giellalt/template-lang-und"
rev_id = 342
template_sha = "e424c1d2f80ec6b0f9d9f55694201f1677e0295b"

[replacements]
__GLOTTOLOG_ID__ = "aleu1260"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-ale"
__UND2C__ = "ale"
__UNDEFINED__ = "Aleut"
__UND__ = "ale"
