template = "https://github.com/giellalt/template-lang-und"
rev_id = 337
template_sha = "eb8f32293ac396653b3977ae5e8a599e4091c885"

[replacements]
__GLOTTOLOG_ID__ = "aleu1260"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-ale"
__UND2C__ = "ale"
__UNDEFINED__ = "Aleut"
__UND__ = "ale"
