template = "https://github.com/giellalt/template-lang-und"
rev_id = 328
template_sha = "a66ce6606ea33e46cd3439c88cafa44d4dcdde92"

[replacements]
__GLOTTOLOG_ID__ = "aleu1260"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-ale"
__UND2C__ = "ale"
__UNDEFINED__ = "Aleut"
__UND__ = "ale"
